In [1]:
import pandas as pd
import numpy as np

In [2]:
df  = pd.read_csv("car_dataset.csv")
df.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [3]:
df.Owner.unique()

array([0, 1, 3])

In [4]:
df.isnull().sum(), df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


(Car_Name         0
 Year             0
 Selling_Price    0
 Present_Price    0
 Kms_Driven       0
 Fuel_Type        0
 Seller_Type      0
 Transmission     0
 Owner            0
 dtype: int64,
 None)

In [5]:
df = df.drop("Car_Name", axis=1)
df["Year"] = df["Year"].max()-df["Year"]
df = pd.get_dummies(df,columns=["Fuel_Type",	"Seller_Type",	"Transmission"],drop_first=True)
df

Year  Selling_Price  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  \
0       4           3.35           5.59       27000      0                 0   
1       5           4.75           9.54       43000      0                 1   
2       1           7.25           9.85        6900      0                 0   
3       7           2.85           4.15        5200      0                 0   
4       4           4.60           6.87       42450      0                 1   
..    ...            ...            ...         ...    ...               ...   
296     2           9.50          11.60       33988      0                 1   
297     3           4.00           5.90       60000      0                 0   
298     9           3.35          11.00       87934      0                 0   
299     1          11.50          12.50        9000      0                 1   
300     2           5.30           5.90        5464      0                 0   

     Fuel_Type_Petrol  Seller_Type_Individual  Transmission_Manual  
0                   1                       0                    1  
1                   0                       0                    1  
2                   1                       0                    1  
3                   1                       0                    1  
4                   0                       0                    1  
..                ...                     ...                  ...  
296                 0                       0                    1  
297                 1                       0                    1  
298                 1                       0                    1  
299                 0                       0                    1  
300                 1                       0                    1  

[301 rows x 9 columns]

In [6]:
X,y = df.drop("Selling_Price",axis=1), df["Selling_Price"]

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
scaler = MinMaxScaler().fit(X)

In [9]:
X=scaler.transform(X)

In [10]:
from xgboost import XGBRegressor
model = XGBRegressor()
model.fit(X,y)
model.score(X,y)

0.9999845130058066

In [11]:
y_pred= model.predict(X)

In [12]:
df["y_pred"] = y_pred

In [13]:
from sklearn.metrics import r2_score, mean_absolute_error

In [15]:
"r2",r2_score(y,y_pred), "mae", mean_absolute_error(y,y_pred)

('r2', 0.9999845130058066, 'mae', 0.014087983362896508)

In [16]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression(normalize=True) # 
lr_model.fit(X,y)
lr_model.score(X,y)

0.8825741581640659

In [17]:
import joblib
joblib.dump(model,open("xgb_model.joblib","wb"))
joblib.dump(scaler,open("scaler.joblib","wb"))
joblib.dump(list(df.drop(["Selling_Price","y_pred"],axis=1).columns),open("columns.joblib","wb"))

In [18]:
sample_one = [{
"Year":2014,
"Selling_Price":3.35,
"Present_Price":5.59,
"Kms_Driven":27000,
"Fuel_Type":"Petrol",
"Seller_Type":"Dealer",
"Transmission":"Manual",
"Owner":0
    }]

In [19]:
columns = joblib.load("columns.joblib")
columns

['Year',
 'Present_Price',
 'Kms_Driven',
 'Owner',
 'Fuel_Type_Diesel',
 'Fuel_Type_Petrol',
 'Seller_Type_Individual',
 'Transmission_Manual']

In [20]:
df_s = pd.DataFrame(sample_one)
df_s

Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type Seller_Type  \
0  2014           3.35           5.59       27000    Petrol      Dealer   

  Transmission  Owner  
0       Manual      0

In [21]:
df_s["Year"] = 2018-df_s["Year"]
df_s = pd.get_dummies(df_s).reindex(columns=columns, fill_value=0)
df_s

Year  Present_Price  Kms_Driven  Owner  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0     4           5.59       27000      0                 0                 1   

   Seller_Type_Individual  Transmission_Manual  
0                       0                    1

In [22]:
scaler = joblib.load(open("scaler.joblib","rb"))
model = joblib.load(open("xgb_model.joblib","rb"))
df_s = scaler.transform(df_s)
res = model.predict(df_s)
res

array([3.3797061], dtype=float32)

In [25]:
sample_two = [{
"Year":2014,
"Present_Price":5.59,
"Kms_Driven":27000,
"Fuel_Type":"Petrol",
"Seller_Type":"Dealer",
"Transmission":"Manual",
"Owner":0
    },
{
"Year":2014,
"Present_Price":5.59,
"Kms_Driven":27000,
"Fuel_Type":"Petrol",
"Seller_Type":"Dealer",
"Transmission":"Manual",
"Owner":0
    }
]

In [26]:
scaler = joblib.load(open("scaler.joblib","rb"))
model = joblib.load(open("xgb_model.joblib","rb"))
columns = joblib.load("columns.joblib")
df_two = pd.DataFrame(sample_two)
df_two["Year"] = 2018-df_two["Year"]
df_two = pd.get_dummies(df_two).reindex(columns=columns, fill_value=0)
df_two = scaler.transform(df_two)
res = model.predict(df_two)
res


array([3.3797061, 3.3797061], dtype=float32)

In [27]:
df.iloc[y_pred.argmax()]

Year                          8.000000
Selling_Price                35.000000
Present_Price                92.600000
Kms_Driven                78000.000000
Owner                         0.000000
Fuel_Type_Diesel              1.000000
Fuel_Type_Petrol              0.000000
Seller_Type_Individual        0.000000
Transmission_Manual           1.000000
y_pred                       34.994293
Name: 86, dtype: float64

In [1]:
import requests

In [3]:
url = "http://44.203.125.165:5000/"
data ={
"make_model":'Audi A3',
"hp_kW":'40',
"km":'1000',
"age":'0',
"gtype":"Automatic",
"gnumber":'5'
    }
response = requests.post(url, json=data)
print(response.text)

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>TypeError: float() argument must be a string or a number, not &#x27;NoneType&#x27; // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css"
        type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does
         not accidentally trigger a request to /favicon.ico which might
         change the application's state. -->
    <link rel="shortcut icon"
        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 140381358519312,
          CONSOLE_MODE = false,
          EVALEX = true,
          EVALEX_TRUSTED = false,
          SECRET = "79tqYA7Wl5xQU2PN3rAn";
    </script>
  </head>
  <body style="background-color: #fff">
 

In [11]:
url = "http://127.0.0.1:5000/api"
data ={
"Year":2014,
"Present_Price":5.59,
"Kms_Driven":27000,
"Fuel_Type":"Petrol",
"Seller_Type":"Dealer",
"Transmission":"Manual",
"Owner":0
    }
response = requests.post(url, json=data)
print(response.text)

{
  "Predicted price": "$ 3.3797"
}

