### LAB 1

In [1]:
import pandas as pd
import numpy as np

In [11]:
a = np.arange(1,9)

In [12]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
b = a[:3]

In [14]:
b[0] = 88

In [15]:
b

array([88,  2,  3])

In [16]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [17]:
c = a.copy()

In [18]:
c[1] = 22

In [19]:
c

array([88, 22,  3,  4,  5,  6,  7,  8])

In [20]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [21]:
a[2] = 100

In [22]:
b

array([ 88,   2, 100])

In [23]:
c

array([88, 22,  3,  4,  5,  6,  7,  8])

In [24]:
a.shape

(8,)

In [26]:
a

array([ 88,   2, 100,   4,   5,   6,   7,   8])

In [25]:
a[::-1]

array([  8,   7,   6,   5,   4, 100,   2,  88])

In [27]:
d = np.array([[1,2,3], [6,7,8]])
d

array([[1, 2, 3],
       [6, 7, 8]])

In [28]:
d[1,1] = 77

In [29]:
d

array([[ 1,  2,  3],
       [ 6, 77,  8]])

In [30]:
d[:2,:2] = 99

In [31]:
d

array([[99, 99,  3],
       [99, 99,  8]])

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [63]:
np.empty((4,4))

array([[2.05833592e-312, 2.33419537e-312, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [50]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [51]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [56]:
np.random.rand(3,3) # 0 ile 1 arasindaki degerleri secer

array([[0.58831774, 0.07921883, 0.50317775],
       [0.42999198, 0.3285222 , 0.99257232],
       [0.846893  , 0.70655393, 0.67123837]])

In [57]:
np.random.randn(3,3) # degerlerin ortalamasi 0 std'si 1 olacak sekilde

array([[ 0.63574755,  2.1118653 ,  0.7613773 ],
       [-1.52101126,  0.89995991, -0.59044381],
       [ 0.05311791, -1.32726203, -1.5644469 ]])

In [58]:
np.random.randint(5,10,size=(3,3))

array([[9, 7, 5],
       [8, 8, 5],
       [6, 6, 9]])

In [65]:
z = np.random.randint(2,15,size=(5,3))
z # 2 dahil 15 dahil degil

array([[13,  5,  8],
       [ 9, 12,  9],
       [ 7,  9,  3],
       [ 7,  5, 10],
       [11,  4,  7]])

In [66]:
z.shape

(5, 3)

In [67]:
z.reshape(3,5)

array([[13,  5,  8,  9, 12],
       [ 9,  7,  9,  3,  7],
       [ 5, 10, 11,  4,  7]])

In [68]:
z.ravel()

array([13,  5,  8,  9, 12,  9,  7,  9,  3,  7,  5, 10, 11,  4,  7])

In [69]:
z.max()

13

In [70]:
np.argmax(z)

0

In [71]:
z.argmin()

8

In [72]:
my_arr = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)
my_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
my_arr1 = np.arange(3,13).reshape(5,2)
my_arr1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [75]:
my_con = np.concatenate((my_arr, my_arr1), axis = 0)
my_con

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [77]:
my_con = np.concatenate((my_arr, my_arr1), axis = 1)
my_con

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [79]:
my_con[1,2:]

array([5, 6])

In [80]:
my_con[1,[2,3]] # kapali parantez icerisine index isimlerini yaziyoruz

array([5, 6])

In [81]:
my_con[[3,1],2]

array([9, 5])

In [82]:
my_con[0:2,1:3]

array([[1, 3],
       [3, 5]])

In [83]:
my_con[:,[0,3]]

array([[ 0,  4],
       [ 2,  6],
       [ 4,  8],
       [ 6, 10],
       [ 8, 12]])

In [84]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [86]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [87]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [88]:
np.stack((a,b)) # yeni bir boyut ekliyor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [89]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
array_1[array_1>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [91]:
array_1[(array_1<10) & (array_1>3)]

array([4, 5, 6, 7, 8, 9])

In [93]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [94]:
x

array([[1, 2],
       [3, 4]])

In [95]:
y

array([[5, 6],
       [7, 8]])

In [96]:
x + y

array([[ 6,  8],
       [10, 12]])

In [97]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [98]:
x * y

array([[ 5, 12],
       [21, 32]])

In [99]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [100]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [101]:
np.power(3,2)

9

In [102]:
np.power(x, y)

array([[    1,    64],
       [ 2187, 65536]])

In [103]:
##########################################################

In [104]:
pd1 = pd.Series([1,2,3,4,5,6,7,8])
pd1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [109]:
labels = ['X','y','z', 'h']
my_list = [5, 10, 15, 20]
arr = np.array([25, 50, 75, 100])
d = {'a': 10, 'b': 20, 'c': 30, 'd':40}

In [110]:
pd.Series(my_list, labels)

X     5
y    10
z    15
h    20
dtype: int64

In [111]:
pd.Series(arr)

0     25
1     50
2     75
3    100
dtype: int64

In [112]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

In [113]:
mix = [7, 'dog', False, np.arange]
pd.Series(mix)

0                             7
1                           dog
2                         False
3    <built-in function arange>
dtype: object

In [115]:
ser = pd.Series([5,10,15,100,25,30], index = ['USA', 'Germany','France', 'UK','Turkey','Greece'])
ser

USA          5
Germany     10
France      15
UK         100
Turkey      25
Greece      30
dtype: int64

In [116]:
ser.sort_values()

USA          5
Germany     10
France      15
Turkey      25
Greece      30
UK         100
dtype: int64

In [117]:
ser.sort_index()

France      15
Germany     10
Greece      30
Turkey      25
UK         100
USA          5
dtype: int64

In [118]:
'Turkey' in ser

True

In [120]:
100 in ser.values

True

In [121]:
ser.isin([100])

USA        False
Germany    False
France     False
UK          True
Turkey     False
Greece     False
dtype: bool

In [122]:
ser.isin([55])

USA        False
Germany    False
France     False
UK         False
Turkey     False
Greece     False
dtype: bool

In [123]:
ser.keys()

Index(['USA', 'Germany', 'France', 'UK', 'Turkey', 'Greece'], dtype='object')

In [128]:
ser.items

<bound method Series.items of USA          5
Germany     10
France      15
UK         100
Turkey      25
Greece      30
dtype: int64>

In [126]:
for key, value in ser.items():
    print(key, value)

USA 5
Germany 10
France 15
UK 100
Turkey 25
Greece 30


In [130]:
m = np.arange(1,30,2).reshape(3,5)
m

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [131]:
df = pd.DataFrame(m)

In [132]:
df

0   1   2   3   4
0   1   3   5   7   9
1  11  13  15  17  19
2  21  23  25  27  29

In [133]:
df = pd.DataFrame(m, columns = ['col1', 'col2', 'col3', 'col4', 'col5'])
df

col1  col2  col3  col4  col5
0     1     3     5     7     9
1    11    13    15    17    19
2    21    23    25    27    29

In [134]:
df.head(2)

col1  col2  col3  col4  col5
0     1     3     5     7     9
1    11    13    15    17    19

In [135]:
df.tail(2)

col1  col2  col3  col4  col5
1    11    13    15    17    19
2    21    23    25    27    29

In [137]:
df.sample(2) # rastgele iki satiri getiriyor

col1  col2  col3  col4  col5
2    21    23    25    27    29
0     1     3     5     7     9